### ISSUE TITLE
Manifestival tests fail to build

### ISSUE THREAD

**Issue by Cynocracy** [manifestival/manifestival#34]
go version
go version go1.14 linux/amd64

go test ./... 

at commit e9d39ec5979318ff82b1047fedafee339575c1b2

k8s.io/client-go/transport
../../../k8s.io/client-go/transport/round_trippers.go:70:11: cannot convert klog.V(9) (type klog.Verbose) to type bool
../../../k8s.io/client-go/transport/round_trippers.go:72:11: cannot convert klog.V(8) (type klog.Verbose) to type bool
../../../k8s.io/client-go/transport/round_trippers.go:74:11: cannot convert klog.V(7) (type klog.Verbose) to type bool
../../../k8s.io/client-go/transport/round_trippers.go:76:11: cannot convert klog.V(6) (type klog.Verbose) to type bool
FAIL    github.com/manifestival/manifestival [build failed]
ok      github.com/manifestival/manifestival/patch      (cached)
ok      github.com/manifestival/manifestival/sources    (cached)
FAIL

**Comment by Cynocracy** [comment]
Needed to `dep ensure` :(

**Comment by jcrossley3** [comment]
Yeah, I need to make that more clear... or better yet, convert to `go modules`. Glad you figured it out.
