### ISSUE TITLE
Do we handle the "selector" of deployment update

### ISSUE THREAD

**Issue by vincent-pli** [manifestival/manifestival#48]
As you know, the `.spec.selector` is immutable after creation of the Deployment in `apps/v1`, to update a existing Depolyment with a different `.spec.selector` will get exception, 
so did we handle the scenario? thanks

**Comment by jcrossley3** [comment]
Hi, thanks for the issue, but how would you suggest we handle that scenario? I'm not sure we want to try to anticipate every possible validation error the server might raise, do we? If the user is going to change the `.spec.selector`, he'll get an error, whether reported by manifestival before the `Apply` or the server after.

Am I misunderstanding the problem?

**Comment by vincent-pli** [comment]
@jcrossley3 
I'm afraid you are right. In this scenario end user need to know more details and should foresee the error and handle it when occurred.

But I think could we supply more option for it, e.g. a `delete/create` option beside `meerged` and `overwrite`?

**Comment by jcrossley3** [comment]
I'm not sure what `merged` is, but that aside, what behavior would the new option provide exactly? How would the code change? A code example might help me understand the problem you're trying to solve: what can't you do now that you'd be able to do with a `delete-create` option?

**Comment by vincent-pli** [comment]
@jcrossley3 
I mean the `ApplyOptions`:
https://github.com/manifestival/manifestival/blob/90ffea819143645c01dca548ff9e9f39b843e45a/client.go#L47-L51

Add one more option beside `Overwrite`, maybe named `DeleteCreate`, the behavior is delete resource first then recreate it when doing apply.

**Comment by jcrossley3** [comment]
Ah, so this is essentially analogous to `kubectl replace` correct? This would be shorthand for:
```go
deployments := manifest.Filter(ByKind("Deployment"))
deployments.Delete()
deployments.Apply()
```
I've considered something like this in the past and ultimately decided it wouldn't add a lot of value over the above. But I'm open. I might prefer to call the option `Replace` just to retain kubectl's terminology. Something like this...
```go
err := manifest.Filter(ByKind("Deployment")).Apply(Replace(true))
```
We could also introduce `Replace` to the interface, e.g.
```go
err := manifest.Filter(ByKind("Deployment")).Replace()
```
Which of those do you prefer?

**Comment by vincent-pli** [comment]
@jcrossley3 
I like `err := manifest.Filter(ByKind("Deployment")).Apply(Replace(true))`

It's more information, a Kubernates `Apply` with `Replace` style.

**Comment by jcrossley3** [comment]
I agree. With the `Replace()` function, we might have to fail if the resources don't exist, like `kubectl replace` does. I'd prefer to `Create` in that case, as `Apply` will. The `Replace` option will essentially bypass the 3-way strategic merge creation, in the same way the `Overwrite` option will in the event of a conflict. That's a pretty subtle distinction between two similarly-named options, but it is at least consistent with `kubectl`.

**Comment by jcrossley3** [comment]
Doing some preliminary testing revealed this may not be trivial to implement, e.g. how long to wait for deleted resources to terminate, whether to delete all before updating any or do them one at a time, and how to deal with server-added immutable fields, like the Services' `spec.clusterIP`. This will require some thought. Feel free to submit a PR if you have the time.

**Comment by vincent-pli** [comment]
@jcrossley3 
Right, I agree with you, I think I can take a look and try to find some solution.

**Comment by jcrossley3** [comment]
Closing since it's subsumed by #74
