### ISSUE TITLE
A few new functions proposed to impement for `type Manifest struct`

### ISSUE THREAD

**Issue by houshengbo** [manifestival/manifestival#49]
```
type Manifest struct {
	resources []unstructured.Unstructured
	Client    Client
	log       logr.Logger
}
```

I propose to have a few functions implemented for this Manifest type.
1. 
```
func (m Manifest) RemoveResources(resources []unstructured.Unstructured) error {
	...
	return nil
}
```
This function will remove all the resources as listed in `resources []unstructured.Unstructured`. After we compare two Manifest, we can generate a list of resources to be delete from the cluster. I think this function should be handy.

2.
```
func (m Manifest) SetResources(resources []unstructured.Unstructured) error {
	...
	return nil
}
```
This function will set all the resources as listed in `resources []unstructured.Unstructured`.  It will overwrite all the existing resources.

3.
```
func (m Manifest) AddResources(resources []unstructured.Unstructured) error {
	...
	return nil
}
```
This function adds the resources into the existing resources in Manifest.

**Comment by houshengbo** [comment]
@jcrossley3 @markusthoemmes

**Comment by markusthoemmes** [comment]
I think a `mf.Manifest` as currently created is immutable. As such, all of the functions shouldn't mutate the current manifest but rather create a new one, with the respective mutations added.

That kinda makes "Remove" and "Set" obsolete. "Remove" is already implemented as "Filter". "Set" is generating a new manifest from a slice.
@jcrossley3 and I discussed the addition of "Append" though, so "Add" in your case would be useful.

**Comment by jcrossley3** [comment]
Yes, what @markusthoemmes said... 

For #1 we could introduce a function that takes a `Manifest`, creates a closure around an index of its resources (keyed by GVK+Namespace+Name, probably) and returns a `Predicate` that can be used to `Filter` another manifest by which resources it has (or not) in common with the first. We could include that function in this library if we think that equality test is sufficient.

And #2 is already implemented: `mf.ManifestFrom(mf.Slice(unstructureds))`. See https://github.com/manifestival/manifestival/blob/master/README.md#sources

For #3, `Append` is already in master and will be included in 0.6.0: https://github.com/manifestival/manifestival/blob/master/README.md#append

**Comment by jcrossley3** [comment]
@houshengbo see if #50 doesn't address your first function

**Comment by houshengbo** [comment]
That PR will resolve this issue. @jcrossley3
