### ISSUE TITLE
Manifestival can not delete namespace create by itself

### ISSUE THREAD

**Issue by vincent-pli** [manifestival/manifestival#61]
I test on `master` branch, the `namespace` create by `Apply()` will not be delete by `Delete()`.

Checked the code, see this part:
https://github.com/manifestival/manifestival/blob/93669fa9179b339d222e56c3652f9d1579860b07/manifestival.go#L219-L225

The `Delete()` only delete `resource` with annotation: `manifestival: new`, and then check here:
https://github.com/manifestival/manifestival/blob/93669fa9179b339d222e56c3652f9d1579860b07/manifestival.go#L133-L137

It's not annotation on the original `resource`, that's why `Delete()` which based on original `resource` not work.

**Comment by jcrossley3** [comment]
I'm pretty sure this is functioning as designed. We don't want manifestival to delete any namespace it didn't create. Otherwise, any resources in that resources that manifestival did NOT create will be deleted, too.

**Comment by vincent-pli** [comment]
@jcrossley3 
The `namespace` is created by manifestival.
Since it has the annotation: `manifestival:  new`, but it cannot be deleted by manifestival, since the original resource in `Manifest.resources` has no such annotation.

**Comment by vincent-pli** [comment]
Another solution is to make query to k8s to get real resource to check the annotation before delete `namespace`.

**Comment by jcrossley3** [comment]
Can you point me to a short reproduceable test case, so I can see it in my environment?

**Comment by jcrossley3** [comment]
Oh, nevermind! I see what you're saying now. I think we used to update the spec and that's why it used to work. I think your PR is correct. Sorry for being dense! :)

**Comment by jcrossley3** [comment]
Fixed by #62
