### ISSUE TITLE
Manifestival DryRun does not properly handle aggregated clusterroles

### ISSUE THREAD

**Issue by Cynocracy** [manifestival/manifestival#72]
We have a situation in which we're attempting to ensure that our installation hasn't been tampered with.

DryRun incorrectly reports a diff of the 'rules' attribute for aggregated clusterroles. This could be a general 'merge lists' issue or something specific to generated fields, I'm not certain.

**Comment by Cynocracy** [comment]
I was told by an engineer on the team that we may actually end up thrashing in these cases, which is.. interesting.

**Comment by jcrossley3** [comment]
What is the correct behavior you're expecting exactly? Do you want `DryRun` to ignore aggregated clusterroles? Personally, I'd prefer the user explicitly filter them out instead.

**Comment by Cynocracy** [comment]
I suppose I'd be happy with 'at parity with kubectl', which does in fact appear to overwrite aggregated clusterroles. Would you look at that. Any thoughts on including it in a predefined set of transforms to allow for a user of DryRun to check 'will this change non-controller owned fields'?

**Comment by jcrossley3** [comment]
I don't understand. If kubectl would overwrite the rules, then current DryRun behavior is correct, right? What would kubectl do that DryRun isn't?

And what's a "non-controller owned field"?

**Comment by Cynocracy** [comment]
Super late comment, but I think you're right that this is working as intended, and with all the improvements to server side apply in the last few years, I doubt this issue is relevant anymore.
