### ISSUE TITLE
Namespace created by ApplyAll() is not deleted by DeleteAll()

### ISSUE THREAD

**Issue by nak3** [manifestival/manifestival#8]
For example, following codes does not remove the namespace created by ApplyAll().

```
const path = "namespace.yaml"

func Apply(api client.Client) error {
        manifest, err := mf.NewManifest(path, false, api)
        if err != nil {
                return err
        }

        if err := manifest.ApplyAll(); err != nil {
                return err
        }
}
```

```
func Delete(api client.Client) error {
        manifest, err := mf.NewManifest(path, false, api)
        if err != nil {
                return err
        }

        if err := manifest.DeleteAll(); err != nil {
                return err
        }
}
```

This is because manifestival deletes namespace only when it has `manifestival: new` annotation as:

https://github.com/manifestival/manifestival/blob/91492e26b01bc846ae01aabfea15413cd004b08f/manifestival.go#L187-L189

But in the above example code, `ApplyAll()` surely adds the annotation, while `DeleteAll()` deletes namespace from yaml file so it does not have the annotation.

Is this `manifestival: new` annotation logic is expected?

**Comment by jcrossley3** [comment]
The logic is supposed to prevent a namespace from being deleted if it already existed when the manifest was first applied. Is that not what you're seeing?

**Comment by jcrossley3** [comment]
I'm closing this as it seems to work as designed. Feel free to re-open if the design itself is a problem. :)
