### ISSUE TITLE
Is cluster-scoped ownership still broken?

### ISSUE THREAD

**Issue by njhill** [manifestival/manifestival#90]
`InjectOwner` currently ignores cluster scoped owners, with the [comment](https://github.com/manifestival/manifestival/blob/master/transform.go#L97-L100):
> // apparently reference counting for cluster-scoped
> // resources is broken, so trust the GC only for ns-scoped
> // dependents

Do you have a reference (excuse the pun) to the source of this statement? Is it really still the case? (looks like the code to skip it has been there for 4+ years at least)

The current [Kubernetes docs](https://kubernetes.io/docs/concepts/architecture/garbage-collection/#owners-dependents) imply that it should work:

> Namespaced dependents can specify cluster-scoped or namespaced owners.

**Comment by jcrossley3** [comment]
Good question! I don't know the answer, but I'm inclined to accept a PR that removes the check. We should error on the side of trusting the developer, I think. :smile: 

It appears https://github.com/kubernetes/kubernetes/issues/54940 is the source and https://github.com/kubernetes/kubernetes/pull/57211 is the fix.

I'm curious: do you have a use case that requires ns-scoped resources to have cluster-scoped parents? Seems like the behavior could be surprising, e.g. cascading deletes.

**Comment by njhill** [comment]
Thanks @jcrossley3. Sure, I can open a PR. We do have such a use case, though I agree it's probably unusual!

**Comment by njhill** [comment]
@jcrossley3 here you go https://github.com/manifestival/manifestival/pull/91
